from s10_common import *
Lf1, Lp1 = pc(A, "frozen_clti", "s4d"), pc(A, "bm3_frozen", "s4d")
Rf1, Rp1 = pc(D, "frozen_clti", "s4d"), pc(D, "bm3_frozen", "s4d")
G2, G2c, Rg = pc(A, "bm3_frozen", "frozen_nogate"), pc(AC, "frozen_clti", "frozen_clti_nogate"), pc(D, "bm3_frozen", "frozen_nogate")
MAf, MAp = pc(AC, "frozen_clti", "frozen_clti_add"), pc(A, "bm3_frozen", "bm3_frozen_add")
allr = [r1(x[0]) for x in Lf1 + Lp1 + Rf1 + Rp1]
dd = diff_of_diff(AC, "frozen_clti", "frozen_clti_nogate", BAND[2], BAND[0])
# ================= discussion =================
Dd = 'sections/discussion.tex'; s = rd(Dd)
a = s.index(r"\textbf{What can be credited?}"); e = s.index(r"\textbf{Why might gating be composition-bound?}")
NEW = r"""\textbf{What can be credited?} Within this Mamba-3 block, on this testbed and with noise-aware training, four statements are supported by independent-noise evidence. (i) Making the scan's dynamics and read/write coefficients input-independent did not remove the block's advantage over S4D on either transition of one dataset: S4D trails the frozen block by """ + f"${min(allr):.0f}$--${max(allr):.0f}$" + r"""\,pp. This does not show that input-dependence is useless: it shows that, in this block and under this budget, learned constants suffice to keep the advantage, and the two readings (``input-dependence contributes nothing here'' and ``what it contributes is recovered by constants'') lead to the same attribution. (ii) The gate-removal cost is large in the partially frozen block (resolved at $-6$\,dB on the original transition and at every level on the reverse one) and in the fully frozen block (resolved at $-6$\,dB). (iii) Without its gate the fully frozen block still exceeds S4D at $0$ and $-2$\,dB, so the gate is not required for a positive advantage there; the removal cost at those levels (""" + sg(G2c[0][0]) + r""" and """ + sg(G2c[1][0]) + r"""\,pp) has intervals that include zero, so a contribution is neither shown nor excluded. At $-6$\,dB the gateless block falls below S4D. (iv) A multiplicative gate exceeds an additive branch of identical size and initial weights by """ + sg(MAf[2][0]) + r"""\,pp at $-6$\,dB in the fully frozen block and by """ + sg(MAp[2][0]) + r"""\,pp in the partially frozen block, whereas the additive arm cannot be distinguished from the gateless one; the pre-specified rescue test is nevertheless not assessable and equivalence is not claimed.

\textbf{Noise-dependent gating.} Only one setting shows a gate contribution that grows significantly with noise depth: the fully frozen block on the original transition (change of the removal cost between $0$ and $-6$\,dB """ + sg(dd[0]) + r"""\,pp, interval excluding zero; Section~\ref{sec:results:depth}). For the partially frozen block, the reverse transition and Paderborn shared bearings the data are compatible with a depth-independent cost, and the statement in the title is restricted to the first case. The depth analysis was added during review and is descriptive.

\textbf{Relation to earlier work.} Representability results for selectivity~\cite{huang2025selectivity} are not contradicted by a single ablation on one testbed. The S4D-superiority finding~\cite{saadatmand2026s4d} was obtained on clean classification benchmarks, without matched noise or a shift of operating condition, so it does not speak to the regime studied here. Two points of contact are nevertheless consistent with it: parity between S4D and the Mamba-style arms on clean data (Appendix~\ref{app:earlier}), and the finding that input-dependent selectivity is not needed for the block's advantage. What this paper adds is specific to the matched-noise, cross-condition regime studied here, not a contradiction of the clean-benchmark result.

\textbf{Implications for backbone selection and for transplant practice.} For practitioners choosing backbones for noisy, drifting signal regimes, the results suggest judging the block as a composition. Whether a gate added to a different host reproduces its effect was tested only under the earlier noise protocol (Appendix~\ref{sec:results:graftwm}): a gate built in the donor's shape recovered no more than an additive branch of the same size on the original transition and somewhat more on the reverse one, and neither design was tuned; we treat this as descriptive. A hypothesis for future work follows: a recomposed block guided by the component map (no conv stem, gate retained, S4D-style $A$) may match or exceed the original on this testbed; we leave it untested, because post-hoc recomposition after seeing the map would not carry the evidential status of the pre-specified chain.

"""
s = s[:a] + NEW + s[e:]
s = s.replace(r"(Section~\ref{sec:results:perclass}), and matched-noise", r"(Appendix~\ref{sec:results:perclass}, earlier protocol), and matched-noise")
wr(Dd, s)
# ================= conclusion =================
Cn = 'sections/conclusion.tex'
CON = r"""\section{Conclusion}
\label{sec:conclusion}

In this Mamba-3 block, on one controlled shift $\times$ noise testbed with matched-noise training and independent training and evaluation noise, making the scan's dynamics and read/write coefficients input-independent did not remove the block's advantage over a time-invariant S4D: the fully frozen block leads by """ + pp3(Lf1) + r"""\,pp on the original transition and by """ + pp3(Rf1) + r"""\,pp on the reverse one. The multiplicative output gate costs most when removed, but this cost is resolved only at $-6$\,dB on the original transition (at every level for the partially frozen block on the reverse one), and without its gate the fully frozen block still exceeds S4D at $0$ and $-2$\,dB. Only in the fully frozen block on the original transition does the gate's contribution grow significantly with noise depth; in the other settings tested the data are compatible with a depth-independent cost. A multiplicative gate exceeds an additive branch of identical size at $-6$\,dB in both hosts, although the pre-specified rescue test is not assessable. On Paderborn the gate-removal cost replicates when bearings are shared between training and evaluation. Grafting a gate onto S4D, per-class results, the stem and $A$ ablations and the disjoint-bearing Paderborn setting were run only under the earlier noise protocol and are descriptive. The evidence rests on one block, one shift pair per dataset, five seeds and final-epoch reporting under a fixed budget. We offer the chain---freeze, remove, replace---as a protocol for turning architecture comparisons into component-level tests, with two cautions from this study: interventions must be matched in width and capacity, and the noise streams of training and evaluation must be independent.
"""
wr(Cn, CON)
# ================= boundaries =================
Bn = 'sections/boundaries.tex'; s = rd(Bn)
def item(start):
    a = s.index(r"\item \textbf{" + start); b = s.index("\n", a); return a, b
def setitem(start, new):
    global s
    a, b = item(start); s = s[:a] + new + s[b:]
setitem("Attribution level.", r"\item \textbf{Attribution level.} Credit assigned to ``the rest of the composition'' is by elimination within the enumerated component set; pairwise interaction terms are not decomposed.")
setitem("The transplant conclusion is budget-conditional.", r"\item \textbf{Transplant results are earlier-protocol and budget-conditional.} The graft onto S4D was run only under the earlier noise protocol, with a matched 50-epoch budget; a longer or graft-tuned budget might recover more, and we make no claim beyond \emph{this gate branch, in this host, under a matched training budget} (Appendix~\ref{sec:results:graft}).")
setitem("Graft dual reading.", r"\item \textbf{Coverage by protocol.} Table~\ref{tab:coverage} states which operations were run under independent noise. Not run under independent noise: the graft onto S4D, the stem and $A$ ablations, additive substitution on the reverse transition, the per-class grid and the disjoint-bearing Paderborn setting. Not run at all: gate removal and additive substitution in the fully frozen block on the reverse transition, and the fully frozen block, additive arm and graft on Paderborn shared bearings.")
setitem("Reporting rule.", r"\item \textbf{Reporting rule.} Reported values are final-epoch macro-F1 under a fixed 50-epoch budget. The best-epoch rule of the original grids, for which the early thresholds were pre-specified, is optimistic by $0.6$--$10.6\pp$ (Appendix~\ref{sec:results:sensitivity}). The final-epoch re-run of the original-design arms (earlier noise protocol) and the independent-noise re-run cover different sets of cells (Table~\ref{tab:coverage}); levels outside the adjudication band and the per-class grid were not re-run. No source-domain validation rule was available, and because the final epoch of the same evaluation condition has been inspected repeatedly, final-epoch values are not a fresh confirmatory test.")
setitem("Scope of the freezing intervention.", r"\item \textbf{Scope of the freezing intervention.} The first freeze arm removes the input-dependence of $\Delta$, $A$, $B$, $C$ only; the fully input-independent scan is a separate grid that was specified after the earlier grids had been seen. No equivalence margin was pre-specified, so ``no measurable cost'' means the point estimates favour the frozen arms with intervals including zero, not equivalence. The value stream and the gate input remain input-dependent, and freezing is implemented inside this Mamba-3 layer; a conclusion about input-dependence in general would need other blocks and tasks.")
setitem("Gate interventions.", r"\item \textbf{Gate interventions.} Under independent noise, gate removal is resolved only at $-6$\,dB in the partially and the fully frozen block on the original transition, and without its gate the fully frozen block still exceeds S4D at $0$ and $-2$\,dB; the combined statement that the fully frozen block's advantage is carried by the gate is therefore not made. Where the gate-removal cost is resolved at every level (partially frozen block, reverse transition) it was not tested in the fully frozen block. The additive substitution could not be distinguished from gate removal, but the multiplicative--additive differences are positive at $-6$\,dB; with gate removal only weakened the pre-specified rescue rule is not assessable, and neither equivalence nor zero rescue is claimed. The rescue ratio is a conditional summary (levels with a denominator below $2\pp$ are excluded in some resamples).")
setitem("Noise protocol.", r"\item \textbf{Noise protocol.} All grids not marked in Table~\ref{tab:coverage} as independent-noise used training and evaluation noise shared by index. Where both protocols exist the arm means differ by at most $4\pp$ and no contrast changed direction, which is not a guarantee for the arms that were not re-run.")
setitem("Strength of the pre-specification evidence.", r"\item \textbf{Strength of the pre-specification evidence.} Thresholds were pre-specified internally; for the follow-up grids from the width-matched graft onwards the thresholds were also committed to a public repository before the first cell, for the earlier grids the evidence is local file times and run-directory names, not an external time-stamped registry (Section~\ref{sec:protocol:prereg}). The noise-depth analysis (Section~\ref{sec:results:depth}) and the multiplicative--additive differences were added during review and are not pre-specified. The process-level repeat check is a single observation.")
setitem("Second dataset.", r"\item \textbf{Second dataset.} On Paderborn, the gate-removal cost replicates when training and evaluation share bearings under independent noise, and the partially frozen block's advantage over S4D is resolved at $-6$\,dB only. With bearings disjoint from the training set (earlier protocol only; per-index label agreement 0.999) nothing replicates and every architecture, S4D included, transferred poorly (47.7--56.9\% against a balanced-chance level of about 50\%). The two Paderborn settings differ in more than bearing overlap, so they do not identify why transfer fails. The fully frozen block was run only in the disjoint setting.")
a, b = item("Sample size."); 
s = s[:a] + r"\item \textbf{Sample size.} Every cell mean uses five seeds. The smallest attainable one-sided Wilcoxon $p$ is $0.031$, paired intervals are wide, and several secondary statements (conv stem, $A$ parameterisation, gateless versus S4D) are not resolved at this size. For the original-design grids conclusions rest on effect sizes that clear the pre-specified thresholds; for the later grids they rest on paired intervals as defined in Section~\ref{sec:protocol:prereg}. Seeds resample initialisation, batch order and noise (evaluation noise is one bank per seed), not bearings." + s[b:]
a, b = item("Testbed scope.")
s = s[:a] + r"\item \textbf{Testbed scope.} All claims are bounded to bearing vibration from one pair of operating conditions of one dataset (37.5\,Hz/11\,kN and 40\,Hz/10\,kN; speed and load both change), binary classification, GPU execution (no edge/real-time claims). Within each direction the training and evaluation bearings are disjoint; the reverse direction uses the same eight bearings with their roles swapped, has a single IR bearing in its evaluation set (the forward direction a single IR bearing in its training set) and so tests direction rather than new bearings; the third condition of the dataset has no IR bearing. The seeds do not resample bearings (Section~\ref{sec:protocol:testbed}), so the intervals carry no bearing-level uncertainty. Further independent datasets and multi-class settings are future work." + s[b:]
wr(Bn, s)
# highlights
H = 'highlights.tex'; h = rd(H); items = re.findall(r"\\item (.*)", h)
new = [f"Input-independent scan coefficients keep a Mamba-3 block {min(allr):.0f}-{max(allr):.0f}pp ahead of S4D.",
       "Gate-removal cost grows with noise depth only in the forward fully frozen block.",
       "A multiplicative gate beats an equal-size additive branch at -6 dB in both hosts.",
       "Core contrasts re-run with independent training and evaluation noise.",
       "Paderborn: gate cost replicates with shared bearings; disjoint bearings do not transfer."]
assert len(items) == 5 and all(len(x) <= 85 for x in new), [len(x) for x in new]
for o, n in zip(items, new): h = h.replace(o, n)
wr(H, h)
print('disc ok')
